### ISSUE TITLE
Function Builder: Basics master checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder-basics#17]
## Design
- [x] **Sim folder and design doc created** (Date: //) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phew-docs account (NOTE: docs are currently in "Function Builder HTML5" folder. EDITED: a Basics folder was created.)
  - [ ] Place design doc in the sim folder (n/a) 
- [x] **Learning goals and standards identified** (Date: //)
- [x] **Design concept complete**  (Date: //)
- [x] **Wireframes complete** (n/a) 
- [ ] **Mockups complete** (n/a) 
  - [x] Mockups or sim checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** (n/a)
- [ ] **Interviews complete** (n/a)  
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 06/06/2017) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide
  - [x] Add an activity
  - [ ] Sim primer draft
  - [x] Verify credits
- [ ] **Post-publication items** 
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 
 
## Implementation
- [x] Repository created (Date: 3/11/17) 
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to chipper/data/ files
- [x] Development started (Date: 4/12/17)
- [x] Sim is "feature complete" (Date: 4/12/17) 
- [x] Code review completed (N/A)
- [x] Published (Date: 6/6/17) 
- [x] README.md updated using `grunt published-readme` (in master and release branch)
 
## QA
- [x] Dev testing started (Date: 4/18/17) 
- [x] Dev testing completed (Date: 5/1/17) 
- [x] RC testing started (Date: 5/1/17)
- [x] RC testing completed (Date: 6/6/17)
- [x] Test matricies put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)

**Comment by pixelzoom** [comment]
@amanda-phet please fill in your bits of the above checklist.

**Comment by pixelzoom** [comment]
All Implementation and QA check list items have been completed. @amanda-phet I believe the remaining items are up to you.

**Comment by amanda-phet** [comment]
@ariel-phet there are a few remaining items I believe you normally do (Features for PhET-iO discussion, Add to Edmodo, Add to Gooru)
